export const dummy = {
  statusCode: 0,
  data: {
    cacheExpiryTime: 320,
    pages: 1,
    pageIndex: 0,
    scrubber: 0,
    filters: [],
    sorts: [
      {
        type: "SortWidget",
        key: "RELEVANCE",
        title: "Relevance",
        selected: 1,
        visible: 1,
        defaultSelection: true,
      },
      {
        type: "SortWidget",
        key: "DELIVERY_TIME",
        title: "Delivery Time",
        selected: 0,
        visible: 1,
        defaultSelection: false,
      },
      {
        type: "SortWidget",
        key: "RATING",
        title: "Rating",
        selected: 0,
        visible: 1,
        defaultSelection: false,
      },
      {
        type: "SortWidget",
        key: "COST_FOR_TWO",
        title: "Cost: Low to High",
        selected: 0,
        visible: 1,
        defaultSelection: false,
      },
      {
        type: "SortWidget",
        key: "COST_FOR_TWO_H2L",
        title: "Cost: High to Low",
        selected: 0,
        visible: 1,
        defaultSelection: false,
      },
    ],
    configs: {
      ribbons: {
        PREORDER: {
          type: "PREORDER",
          text: "Preorder",
          textColor: "#ffffff",
          imageId: "sfefefefeegeg",
          topBackgroundColor: "#d53d4c",
          bottomBackgroundColor: "#af2330",
          priority: 3,
        },
        EXCLUSIVE: {
          type: "EXCLUSIVE",
          text: "Exclusive",
          textColor: "#ffffff",
          imageId: "sfefefefeegeg",
          topBackgroundColor: "#fa4a5b",
          bottomBackgroundColor: "#d12a3b",
          priority: 2,
        },
        NEW: {
          type: "NEW",
          text: "Newly Added",
          textColor: "#ffffff",
          imageId: "sfefefefeegeg",
          topBackgroundColor: "#d53d4c",
          bottomBackgroundColor: "#af2330",
          priority: 4,
        },
        REPEAT: {
          type: "REPEAT",
          text: "Repeat",
          textColor: "#ffffff",
          imageId: "sfefefefeegeg",
          topBackgroundColor: "#D53D4C",
          bottomBackgroundColor: "#B02331",
          priority: 6,
        },
        CLOUD: {
          type: "CLOUD",
          text: "Daily Menus",
          textColor: "#ffffff",
          imageId: "sfefefefeegeg",
          topBackgroundColor: "#fa4a5b",
          bottomBackgroundColor: "#d12a3b",
          priority: 5,
        },
        PREMIUM: {
          type: "PREMIUM",
          text: "Premium",
          textColor: "#ffffff",
          imageId: "sfefefefeegeg",
          topBackgroundColor: "#8a584b",
          bottomBackgroundColor: "#583229",
          priority: 7,
        },
        PROMOTED: {
          type: "PROMOTED",
          text: "Promoted",
          textColor: "#ffffff",
          imageId: "sfefefefeegeg",
          topBackgroundColor: "#3a3c41",
          bottomBackgroundColor: "#1e2023",
          priority: 1,
        },
      },
      croutons: {
        RAIN: {
          type: "Crouton",
          bgColor: "#282C3F",
          icon: "surge_listing_piuzrv",
          textColor: "#ffffff",
          title: "Bad Weather",
          message: "${amount} extra levied on some restaurants",
        },
        SERVICEABLE_WITH_BANNER_RAIN: {
          type: "Crouton",
          bgColor: "#282C3F",
          icon: "rain_crouton_4x",
          textColor: "#ffffff",
          title: "Bad Weather",
          message: "Few restaurants unserviceable due to rains",
        },
      },
    },
    cards: [
      {
        cardType: "seeAllRestaurants",
        layoutAlignmentType: "VERTICAL",
        data: {
          type: "seeAllRestaurants",
          data: {
            title: "SEE ALL",
            totalOpenRestaurants: 0,
            cards: [
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "527655",
                  name: "SRI RED CHILLI",
                  uuid: "60ddc25f-cbb6-4f91-be68-13f3860c1ed5",
                  city: "75",
                  area: "Hanamkonda",
                  totalRatingsString: "Too Few Ratings",
                  cloudinaryImageId: "z6qjwczlrcuiqgcb6ear",
                  cuisines: ["Chinese", "Snacks"],
                  tags: [],
                  costForTwo: 15000,
                  costForTwoString: "₹150 FOR TWO",
                  deliveryTime: 36,
                  minDeliveryTime: 36,
                  maxDeliveryTime: 36,
                  slaString: "36 MINS",
                  lastMileTravel: 9,
                  slugs: {
                    restaurant: "sri-red-chilli-hanamkonda-hanamkonda",
                    city: "warangal",
                  },
                  cityState: "75",
                  address:
                    "3-9-247/9 YADAVA NAGAR KUMARPALLE HANAMKONDA  WARANGAL 506001",
                  locality: "Yadava Nagar",
                  parentId: 317956,
                  unserviceable: true,
                  veg: false,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  chain: [],
                  feeDetails: {
                    fees: [
                      { name: "distance", fee: 5200, message: "" },
                      { name: "time", fee: 1000, message: "" },
                      { name: "special", fee: 0, message: "" },
                    ],
                    totalFees: 6200,
                    message: "",
                    title: "Delivery Charge",
                    amount: "6200",
                    icon: "",
                  },
                  availability: {
                    opened: false,
                    nextOpenMessage: "Opens next at 10:50 am, today",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID: "",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "9 kms",
                  hasSurge: false,
                  sla: {
                    restaurantId: "527655",
                    deliveryTime: 36,
                    minDeliveryTime: 36,
                    maxDeliveryTime: 36,
                    lastMileTravel: 9,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE_WITH_BANNER",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: false,
                  avgRating: "--",
                  totalRatings: 0,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "480615",
                  name: "THE COFFEE HOUSE",
                  uuid: "4658648b-9d3f-47c7-bfb7-7f07ea7ad205",
                  city: "75",
                  area: "Hanamkonda",
                  totalRatingsString: "20+ ratings",
                  cloudinaryImageId: "fdje22hy952hhljooyle",
                  cuisines: ["Snacks", "Pizzas", "American"],
                  tags: [],
                  costForTwo: 15000,
                  costForTwoString: "₹150 FOR TWO",
                  deliveryTime: 35,
                  minDeliveryTime: 35,
                  maxDeliveryTime: 35,
                  slaString: "35 MINS",
                  lastMileTravel: 8.899999618530273,
                  slugs: {
                    restaurant: "the-coffee-house-hanamkonda-hanamkonda",
                    city: "warangal",
                  },
                  cityState: "75",
                  address: "Plot no 5-9-1,Kishanpura,Hanamkonda",
                  locality: "Kishanpura",
                  parentId: 207109,
                  unserviceable: true,
                  veg: false,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  chain: [],
                  feeDetails: {
                    fees: [
                      { name: "distance", fee: 5200, message: "" },
                      { name: "time", fee: 1000, message: "" },
                      { name: "special", fee: 0, message: "" },
                    ],
                    totalFees: 6200,
                    message: "",
                    title: "Delivery Charge",
                    amount: "6200",
                    icon: "",
                  },
                  availability: {
                    opened: false,
                    nextOpenMessage: "Opens next at 10:59 am, today",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID: "",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "8.8 kms",
                  hasSurge: false,
                  sla: {
                    restaurantId: "480615",
                    deliveryTime: 35,
                    minDeliveryTime: 35,
                    maxDeliveryTime: 35,
                    lastMileTravel: 8.899999618530273,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE_WITH_BANNER",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: false,
                  avgRating: "3.0",
                  totalRatings: 20,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "99275",
                  name: "Om Sai Ram Tiffins",
                  uuid: "6fb00940-5e44-4ba1-ad6f-9cee53a06e0b",
                  city: "75",
                  area: "Hanamakonda",
                  totalRatingsString: "5000+ ratings",
                  cloudinaryImageId: "ujfum7lwnu5v3stjfaoi",
                  cuisines: ["South Indian"],
                  tags: [],
                  costForTwo: 10000,
                  costForTwoString: "₹100 FOR TWO",
                  deliveryTime: 30,
                  minDeliveryTime: 30,
                  maxDeliveryTime: 30,
                  slaString: "30 MINS",
                  lastMileTravel: 10.100000381469727,
                  slugs: {
                    restaurant: "om-sai-ram-tiffins-kuc-x-road-hanamkonda",
                    city: "warangal",
                  },
                  cityState: "75",
                  address: "5-11-503&504 C/G-6 NEAR KU HANAMKONDA",
                  locality: "Kakatiya University Road",
                  parentId: 18954,
                  unserviceable: true,
                  veg: true,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  aggregatedDiscountInfo: {
                    header: "10% off",
                    shortDescriptionList: [
                      {
                        meta: "10% off | Use TRYNEW",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                      },
                    ],
                    descriptionList: [
                      {
                        meta: "10% off up to ₹40 | Use code TRYNEW",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                      },
                    ],
                    subHeader: "",
                    headerType: 0,
                    superFreedel: "",
                  },
                  aggregatedDiscountInfoV2: {
                    header: "10% OFF",
                    shortDescriptionList: [
                      {
                        meta: "Use TRYNEW",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                      },
                    ],
                    descriptionList: [
                      {
                        meta: "10% off up to ₹40 | Use code TRYNEW",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                      },
                    ],
                    subHeader: "",
                    headerType: 0,
                    superFreedel: "",
                  },
                  chain: [],
                  feeDetails: {
                    fees: [
                      { name: "distance", fee: 6200, message: "" },
                      { name: "time", fee: 1000, message: "" },
                      { name: "special", fee: 0, message: "" },
                    ],
                    totalFees: 7200,
                    message: "",
                    title: "Delivery Charge",
                    amount: "7200",
                    icon: "",
                  },
                  availability: {
                    opened: false,
                    nextOpenMessage: "Opens next at 7 am, today",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 1,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID: "",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "10.1 kms",
                  hasSurge: false,
                  sla: {
                    restaurantId: "99275",
                    deliveryTime: 30,
                    minDeliveryTime: 30,
                    maxDeliveryTime: 30,
                    lastMileTravel: 10.100000381469727,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE_WITH_BANNER",
                    rainMode: "NONE",
                    longDistance: "IT_IS_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: false,
                  avgRating: "4.0",
                  totalRatings: 5000,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "519922",
                  name: "EAT N TREAT",
                  uuid: "f1cd4c32-29bd-4c68-baa9-7400ba64da79",
                  city: "75",
                  area: "Hanamkonda",
                  totalRatingsString: "Too Few Ratings",
                  cloudinaryImageId: "jdhkye6zbuaxhvt2pzfz",
                  cuisines: ["Indian"],
                  tags: [],
                  costForTwo: 15000,
                  costForTwoString: "₹150 FOR TWO",
                  deliveryTime: 38,
                  minDeliveryTime: 38,
                  maxDeliveryTime: 38,
                  slaString: "38 MINS",
                  lastMileTravel: 10,
                  slugs: {
                    restaurant: "eat-n-treat-hanamkonda-hanamkonda",
                    city: "warangal",
                  },
                  cityState: "75",
                  address:
                    "2-5-854/2 CIRCUIT HOUSE RD HANAMKONDA WARANGAL 506001",
                  locality: "Circuit House Road",
                  parentId: 76042,
                  unserviceable: true,
                  veg: false,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  chain: [],
                  feeDetails: {
                    fees: [
                      { name: "time", fee: 1000, message: "" },
                      { name: "distance", fee: 6200, message: "" },
                      { name: "special", fee: 0, message: "" },
                    ],
                    totalFees: 7200,
                    message: "",
                    title: "Delivery Charge",
                    amount: "7200",
                    icon: "",
                  },
                  availability: {
                    opened: false,
                    nextOpenMessage: "Opens next at 11 am, today",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 1,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID: "",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "10 kms",
                  hasSurge: false,
                  sla: {
                    restaurantId: "519922",
                    deliveryTime: 38,
                    minDeliveryTime: 38,
                    maxDeliveryTime: 38,
                    lastMileTravel: 10,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE_WITH_BANNER",
                    rainMode: "NONE",
                    longDistance: "IT_IS_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: false,
                  avgRating: "--",
                  totalRatings: 0,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "673488",
                  name: "Hasini Sugarcane Juice\t",
                  uuid: "150c4967-5055-4884-b58b-e5447e61cc48",
                  city: "75",
                  area: "Hanamkonda",
                  totalRatingsString: "Too Few Ratings",
                  cloudinaryImageId: "56d9a7a0d7b100161dab44fc881dee1d",
                  cuisines: ["Beverages"],
                  tags: [],
                  costForTwo: 13000,
                  costForTwoString: "₹130 FOR TWO",
                  deliveryTime: 33,
                  minDeliveryTime: 33,
                  maxDeliveryTime: 33,
                  slaString: "33 MINS",
                  lastMileTravel: 9.100000381469727,
                  slugs: {
                    restaurant: "hasini-sugarcane-juice-hanamkonda-hanamkonda",
                    city: "warangal",
                  },
                  cityState: "75",
                  address:
                    "opposit B.Ed college, 5-6-95, Main Rd, Lashkar Bazar, Kishanpura, Hanamkonda, Telangana 506001, India",
                  locality: "Lashkar Bazar",
                  parentId: 403211,
                  unserviceable: true,
                  veg: true,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  aggregatedDiscountInfo: {
                    header: "30% off",
                    shortDescriptionList: [
                      {
                        meta: "30% off | Use JUMBO",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                      },
                    ],
                    descriptionList: [
                      {
                        meta: "30% off up to ₹150 on orders above ₹400 | Use code JUMBO",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                      },
                    ],
                    subHeader: "",
                    headerType: 0,
                    superFreedel: "",
                  },
                  aggregatedDiscountInfoV2: {
                    header: "30% OFF",
                    shortDescriptionList: [
                      {
                        meta: "Use JUMBO",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                      },
                    ],
                    descriptionList: [
                      {
                        meta: "30% off up to ₹150 on orders above ₹400 | Use code JUMBO",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                      },
                    ],
                    subHeader: "",
                    headerType: 0,
                    superFreedel: "",
                  },
                  chain: [],
                  feeDetails: {
                    fees: [
                      { name: "distance", fee: 5200, message: "" },
                      { name: "time", fee: 1000, message: "" },
                      { name: "special", fee: 0, message: "" },
                    ],
                    totalFees: 6200,
                    message: "",
                    title: "Delivery Charge",
                    amount: "6200",
                    icon: "",
                  },
                  availability: {
                    opened: false,
                    nextOpenMessage: "Opens next at 10 am, today",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID: "",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "9.1 kms",
                  hasSurge: false,
                  sla: {
                    restaurantId: "673488",
                    deliveryTime: 33,
                    minDeliveryTime: 33,
                    maxDeliveryTime: 33,
                    lastMileTravel: 9.100000381469727,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE_WITH_BANNER",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: false,
                  avgRating: "--",
                  totalRatings: 0,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "664762",
                  name: "Thick Shake Factory\t",
                  uuid: "9dbc31f4-2e0b-4e5e-979c-5baa80019fa4",
                  city: "75",
                  area: "Hanamkonda",
                  totalRatingsString: "Too Few Ratings",
                  cloudinaryImageId: "ee70173283ac8519381038efb80da5c5",
                  cuisines: ["Fast Food"],
                  tags: [],
                  costForTwo: 15900,
                  costForTwoString: "₹159 FOR TWO",
                  deliveryTime: 38,
                  minDeliveryTime: 38,
                  maxDeliveryTime: 38,
                  slaString: "38 MINS",
                  lastMileTravel: 11.300000190734863,
                  slugs: {
                    restaurant: "thick-shake-factory-hanamkonda-hanamkonda",
                    city: "warangal",
                  },
                  cityState: "75",
                  address:
                    "2G4Q+WGV, TNGOS Colony Rd, Phase 2, Srinagar Colony, Hanamkonda, Telangana 506001, India",
                  locality: "Srinagar Colony",
                  parentId: 1041,
                  unserviceable: true,
                  veg: false,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  chain: [],
                  feeDetails: {
                    fees: [
                      { name: "distance", fee: 6200, message: "" },
                      { name: "time", fee: 1000, message: "" },
                      { name: "special", fee: 0, message: "" },
                    ],
                    totalFees: 7200,
                    message: "",
                    title: "Delivery Charge",
                    amount: "7200",
                    icon: "",
                  },
                  availability: {
                    opened: false,
                    nextOpenMessage: "Opens next at 6:30 pm, Monday",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 1,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID: "",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "11.3 kms",
                  hasSurge: false,
                  sla: {
                    restaurantId: "664762",
                    deliveryTime: 38,
                    minDeliveryTime: 38,
                    maxDeliveryTime: 38,
                    lastMileTravel: 11.300000190734863,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE_WITH_BANNER",
                    rainMode: "NONE",
                    longDistance: "IT_IS_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: false,
                  avgRating: "--",
                  totalRatings: 0,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "88245",
                  name: "Surabhi Food Forest",
                  uuid: "73a35e96-89d6-444a-8dca-76ac61c4a205",
                  city: "75",
                  area: "Hanamakonda",
                  totalRatingsString: "5000+ ratings",
                  cloudinaryImageId: "Swiggy-Dash/aau3bllshofiku5tyubg",
                  cuisines: ["Bakery"],
                  tags: [],
                  costForTwo: 15000,
                  costForTwoString: "₹150 FOR TWO",
                  deliveryTime: 31,
                  minDeliveryTime: 31,
                  maxDeliveryTime: 31,
                  slaString: "31 MINS",
                  lastMileTravel: 11.600000381469727,
                  slugs: {
                    restaurant:
                      "surabhi-food-forest-chaitanyapuri-colony-hanamkonda",
                    city: "warangal",
                  },
                  cityState: "75",
                  address: "opp tara gardens,rec, hanamkonda",
                  locality: "Prashanthnagar Colony",
                  parentId: 197649,
                  unserviceable: true,
                  veg: false,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  aggregatedDiscountInfo: {
                    header: "30% off",
                    shortDescriptionList: [
                      {
                        meta: "30% off | Use TRYNEW",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                      },
                    ],
                    descriptionList: [
                      {
                        meta: "30% off up to ₹75 | Use code TRYNEW",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                      },
                    ],
                    subHeader: "",
                    headerType: 0,
                    superFreedel: "",
                  },
                  aggregatedDiscountInfoV2: {
                    header: "30% OFF",
                    shortDescriptionList: [
                      {
                        meta: "Use TRYNEW",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                      },
                    ],
                    descriptionList: [
                      {
                        meta: "30% off up to ₹75 | Use code TRYNEW",
                        discountType: "Percentage",
                        operationType: "RESTAURANT",
                      },
                    ],
                    subHeader: "",
                    headerType: 0,
                    superFreedel: "",
                  },
                  chain: [],
                  feeDetails: {
                    fees: [
                      { name: "distance", fee: 6200, message: "" },
                      { name: "time", fee: 1000, message: "" },
                      { name: "special", fee: 0, message: "" },
                    ],
                    totalFees: 7200,
                    message: "",
                    title: "Delivery Charge",
                    amount: "7200",
                    icon: "",
                  },
                  availability: {
                    opened: false,
                    nextOpenMessage: "Opens next at 11 am, today",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 1,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID: "",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "11.6 kms",
                  hasSurge: false,
                  sla: {
                    restaurantId: "88245",
                    deliveryTime: 31,
                    minDeliveryTime: 31,
                    maxDeliveryTime: 31,
                    lastMileTravel: 11.600000381469727,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE_WITH_BANNER",
                    rainMode: "NONE",
                    longDistance: "IT_IS_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: false,
                  avgRating: "3.4",
                  totalRatings: 5000,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "665521",
                  name: "FOOD ON FIRE",
                  uuid: "f3865a01-79dd-4a57-830c-ab10cfdea88e",
                  city: "75",
                  area: "Hanamkonda",
                  totalRatingsString: "Too Few Ratings",
                  cloudinaryImageId: "013749cfa49096c8d4db9bf0e3309d48",
                  cuisines: ["North Indian", "Biryani", "Chinese"],
                  tags: [],
                  costForTwo: 60000,
                  costForTwoString: "₹600 FOR TWO",
                  deliveryTime: 35,
                  minDeliveryTime: 35,
                  maxDeliveryTime: 35,
                  slaString: "35 MINS",
                  lastMileTravel: 9.600000381469727,
                  slugs: {
                    restaurant: "food-and-fire-hanamkonda-hanamkonda",
                    city: "warangal",
                  },
                  cityState: "75",
                  address:
                    "2H74+QH9, Nayeem Nagar, Jagruti Colony, Naim Nagar, Hanamkonda, Telangana 506009, India",
                  locality: "Jagruti Colony",
                  parentId: 80915,
                  unserviceable: true,
                  veg: false,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  chain: [],
                  feeDetails: {
                    fees: [
                      { name: "distance", fee: 5200, message: "" },
                      { name: "time", fee: 1000, message: "" },
                      { name: "special", fee: 0, message: "" },
                    ],
                    totalFees: 6200,
                    message: "",
                    title: "Delivery Charge",
                    amount: "6200",
                    icon: "",
                  },
                  availability: {
                    opened: false,
                    nextOpenMessage: "Opens next at 12 noon, today",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID: "",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "9.6 kms",
                  hasSurge: false,
                  sla: {
                    restaurantId: "665521",
                    deliveryTime: 35,
                    minDeliveryTime: 35,
                    maxDeliveryTime: 35,
                    lastMileTravel: 9.600000381469727,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE_WITH_BANNER",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: false,
                  avgRating: "--",
                  totalRatings: 0,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "620939",
                  name: "Sholay Dosa Dukaan",
                  uuid: "e69bf963-e34f-4594-a96c-b47f95af105e",
                  city: "75",
                  area: "Hanamkonda",
                  totalRatingsString: "Too Few Ratings",
                  cloudinaryImageId: "remnqvpnfjsi61qxhklt",
                  cuisines: ["South Indian"],
                  tags: [],
                  costForTwo: 15000,
                  costForTwoString: "₹150 FOR TWO",
                  deliveryTime: 38,
                  minDeliveryTime: 38,
                  maxDeliveryTime: 38,
                  slaString: "38 MINS",
                  lastMileTravel: 10.600000381469727,
                  slugs: {
                    restaurant: "sholay-dosa-dukaan-hanamkonda-hanamkonda",
                    city: "warangal",
                  },
                  cityState: "75",
                  address: "2-7-263,Excise Colony,Hanamkonda,Warangal  506001",
                  locality: "Excise Colony",
                  parentId: 369937,
                  unserviceable: true,
                  veg: false,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  chain: [],
                  feeDetails: {
                    fees: [
                      { name: "distance", fee: 6200, message: "" },
                      { name: "time", fee: 1000, message: "" },
                      { name: "special", fee: 0, message: "" },
                    ],
                    totalFees: 7200,
                    message: "",
                    title: "Delivery Charge",
                    amount: "7200",
                    icon: "",
                  },
                  availability: {
                    opened: false,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID: "",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "10.6 kms",
                  hasSurge: false,
                  sla: {
                    restaurantId: "620939",
                    deliveryTime: 38,
                    minDeliveryTime: 38,
                    maxDeliveryTime: 38,
                    lastMileTravel: 10.600000381469727,
                    lastMileDistance: 0,
                    serviceability: "NON_SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: false,
                  avgRating: "--",
                  totalRatings: 0,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "676725",
                  name: "Laxmiganapathi Biryani  Point",
                  uuid: "519130b5-3023-4912-8405-f9eec6b69c41",
                  city: "75",
                  area: "Hanamkonda",
                  totalRatingsString: "Too Few Ratings",
                  cloudinaryImageId: "68781d86c08a707aa5bdfe9fd2a62500",
                  cuisines: ["Biryani"],
                  tags: [],
                  costForTwo: 10000,
                  costForTwoString: "₹100 FOR TWO",
                  deliveryTime: 35,
                  minDeliveryTime: 35,
                  maxDeliveryTime: 35,
                  slaString: "35 MINS",
                  lastMileTravel: 8.600000381469727,
                  slugs: {
                    restaurant:
                      "laxmiganapathi-biryani-point-hanamkonda-hanamkonda",
                    city: "warangal",
                  },
                  cityState: "75",
                  address:
                    "H-NO:6-2-57, NEAR  HANUMAKONDA BUSSTAND,,  Warangal (Town), Warangal, ,  Telangana, 506001",
                  locality: "Hanumakonda busstand",
                  parentId: 405520,
                  unserviceable: true,
                  veg: false,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  chain: [],
                  feeDetails: {
                    fees: [
                      { name: "distance", fee: 5200, message: "" },
                      { name: "time", fee: 1000, message: "" },
                      { name: "special", fee: 0, message: "" },
                    ],
                    totalFees: 6200,
                    message: "",
                    title: "Delivery Charge",
                    amount: "6200",
                    icon: "",
                  },
                  availability: {
                    opened: false,
                    nextOpenMessage: "Opens next at 10:45 am, today",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID: "",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "8.6 kms",
                  hasSurge: false,
                  sla: {
                    restaurantId: "676725",
                    deliveryTime: 35,
                    minDeliveryTime: 35,
                    maxDeliveryTime: 35,
                    lastMileTravel: 8.600000381469727,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE_WITH_BANNER",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: false,
                  avgRating: "--",
                  totalRatings: 0,
                  new: true,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "89373",
                  name: "Akshay tiffins",
                  uuid: "780bcf77-843e-4a6d-affc-08760e768a8a",
                  city: "75",
                  area: "Hanamakonda",
                  totalRatingsString: "10000+ ratings",
                  cloudinaryImageId: "bxc32vivxysgcgpzizgu",
                  cuisines: ["South Indian", "North Indian"],
                  tags: [],
                  costForTwo: 10000,
                  costForTwoString: "₹100 FOR TWO",
                  deliveryTime: 29,
                  minDeliveryTime: 29,
                  maxDeliveryTime: 29,
                  slaString: "29 MINS",
                  lastMileTravel: 10.100000381469727,
                  slugs: {
                    restaurant: "akshaya-tiffins-subedari-hanamkonda",
                    city: "warangal",
                  },
                  cityState: "75",
                  address: "beside rohini hospital,subedari",
                  locality: "Rohini Hospital Road",
                  parentId: 28696,
                  unserviceable: true,
                  veg: true,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  chain: [],
                  feeDetails: {
                    fees: [
                      { name: "distance", fee: 6200, message: "" },
                      { name: "time", fee: 1000, message: "" },
                      { name: "special", fee: 0, message: "" },
                    ],
                    totalFees: 7200,
                    message: "",
                    title: "Delivery Charge",
                    amount: "7200",
                    icon: "",
                  },
                  availability: {
                    opened: false,
                    nextOpenMessage: "Opens next at 7 am, today",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID: "",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "10.1 kms",
                  hasSurge: false,
                  sla: {
                    restaurantId: "89373",
                    deliveryTime: 29,
                    minDeliveryTime: 29,
                    maxDeliveryTime: 29,
                    lastMileTravel: 10.100000381469727,
                    lastMileDistance: 0,
                    serviceability: "NON_SERVICEABLE",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: false,
                  avgRating: "4.2",
                  totalRatings: 10000,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "602023",
                  name: "Let's Scoop Ice Cream Cafe",
                  uuid: "426c00a3-fece-4459-b7e0-13e182abefc2",
                  city: "75",
                  area: "Hanamkonda",
                  totalRatingsString: "20+ ratings",
                  cloudinaryImageId: "lx8ifr6uxqce8y1yxlns",
                  cuisines: [
                    "Ice Cream",
                    "Desserts",
                    "Fast Food",
                    "Beverages",
                    "Italian",
                  ],
                  tags: [],
                  costForTwo: 20000,
                  costForTwoString: "₹200 FOR TWO",
                  deliveryTime: 38,
                  minDeliveryTime: 38,
                  maxDeliveryTime: 38,
                  slaString: "38 MINS",
                  lastMileTravel: 12.5,
                  slugs: {
                    restaurant: "na-enterprises-hanamkonda-hanamkonda",
                    city: "warangal",
                  },
                  cityState: "75",
                  address:
                    "near NIT, Fathimanagar, Hanamkonda, Telangana 502004, India",
                  locality: "Fathimanagar",
                  parentId: 388121,
                  unserviceable: true,
                  veg: true,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  chain: [],
                  feeDetails: {
                    fees: [
                      { name: "distance", fee: 6200, message: "" },
                      { name: "time", fee: 1000, message: "" },
                      { name: "special", fee: 0, message: "" },
                    ],
                    totalFees: 7200,
                    message: "",
                    title: "Delivery Charge",
                    amount: "7200",
                    icon: "",
                  },
                  availability: {
                    opened: false,
                    nextOpenMessage: "Opens next at 11 am, today",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 1,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID: "",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "12.5 kms",
                  hasSurge: false,
                  sla: {
                    restaurantId: "602023",
                    deliveryTime: 38,
                    minDeliveryTime: 38,
                    maxDeliveryTime: 38,
                    lastMileTravel: 12.5,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE_WITH_BANNER",
                    rainMode: "NONE",
                    longDistance: "IT_IS_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: false,
                  avgRating: "4.0",
                  totalRatings: 20,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "485083",
                  name: "Inn Biryani & Fast Food",
                  uuid: "ca2c4b13-4709-4e22-b0e3-0eb9350f45b5",
                  city: "75",
                  area: "Hanamakonda",
                  totalRatingsString: "Too Few Ratings",
                  cloudinaryImageId: "uxmzbaz293cikxwtrnz6",
                  cuisines: ["Biryani", "Indian", "Chinese"],
                  tags: [],
                  costForTwo: 20000,
                  costForTwoString: "₹200 FOR TWO",
                  deliveryTime: 38,
                  minDeliveryTime: 38,
                  maxDeliveryTime: 38,
                  slaString: "38 MINS",
                  lastMileTravel: 11.300000190734863,
                  slugs: {
                    restaurant: "inn-biryani-&-fast-food-hanamkonda-hanamkonda",
                    city: "warangal",
                  },
                  cityState: "75",
                  address:
                    "H.No 2-12-241, Vidyaranyapuri, Oppsite KU 2nd gate, palvelpula Hanamkonda Warangal",
                  locality: "Vidyaranyapuri",
                  parentId: 291366,
                  unserviceable: true,
                  veg: false,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  chain: [],
                  feeDetails: {
                    fees: [
                      { name: "distance", fee: 6200, message: "" },
                      { name: "time", fee: 1000, message: "" },
                      { name: "special", fee: 0, message: "" },
                    ],
                    totalFees: 7200,
                    message: "",
                    title: "Delivery Charge",
                    amount: "7200",
                    icon: "",
                  },
                  availability: {
                    opened: false,
                    nextOpenMessage: "Opens next at 12 noon, today",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 1,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID: "",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "11.3 kms",
                  hasSurge: false,
                  sla: {
                    restaurantId: "485083",
                    deliveryTime: 38,
                    minDeliveryTime: 38,
                    maxDeliveryTime: 38,
                    lastMileTravel: 11.300000190734863,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE_WITH_BANNER",
                    rainMode: "NONE",
                    longDistance: "IT_IS_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: false,
                  avgRating: "--",
                  totalRatings: 0,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "549423",
                  name: "KAKATHIYA CUISINE FAMILY RESTAURANT",
                  uuid: "4725347c-ab35-4408-a703-910008054e34",
                  city: "75",
                  area: "Mathwada",
                  totalRatingsString: "20+ ratings",
                  cloudinaryImageId: "sfoq6j2jnhl6tekeyyyk",
                  cuisines: ["North Indian", "Chinese", "Snacks", "Beverages"],
                  tags: [],
                  costForTwo: 15000,
                  costForTwoString: "₹150 FOR TWO",
                  deliveryTime: 31,
                  minDeliveryTime: 31,
                  maxDeliveryTime: 31,
                  slaString: "31 MINS",
                  lastMileTravel: 4.800000190734863,
                  slugs: {
                    restaurant:
                      "kakathiya-cuisine-family-restaurant-warangal-warangal",
                    city: "warangal",
                  },
                  cityState: "75",
                  address: "20-9-117 WARANGAL",
                  locality: "Warangal Fort",
                  parentId: 330279,
                  unserviceable: true,
                  veg: false,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  chain: [],
                  feeDetails: {
                    fees: [
                      { name: "distance", fee: 2400, message: "" },
                      { name: "time", fee: 1000, message: "" },
                      { name: "special", fee: 0, message: "" },
                    ],
                    totalFees: 3400,
                    message: "",
                    title: "Delivery Charge",
                    amount: "3400",
                    icon: "",
                  },
                  availability: {
                    opened: false,
                    nextOpenMessage: "Opens next at 12 noon, today",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID: "",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "4.8 kms",
                  hasSurge: false,
                  sla: {
                    restaurantId: "549423",
                    deliveryTime: 31,
                    minDeliveryTime: 31,
                    maxDeliveryTime: 31,
                    lastMileTravel: 4.800000190734863,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE_WITH_BANNER",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: false,
                  avgRating: "3.2",
                  totalRatings: 20,
                  new: false,
                },
                subtype: "basic",
              },
              {
                type: "restaurant",
                data: {
                  type: "F",
                  id: "697427",
                  name: "SAG Bucket Biryani",
                  uuid: "6817edf7-6070-440e-bc5f-30a2276365da",
                  city: "75",
                  area: "Hanamkonda",
                  totalRatingsString: "Too Few Ratings",
                  cloudinaryImageId: "da2592e0d25f079cbf9aedf436cabf6f",
                  cuisines: ["Biryani"],
                  tags: [],
                  costForTwo: 34000,
                  costForTwoString: "₹340 FOR TWO",
                  deliveryTime: 33,
                  minDeliveryTime: 33,
                  maxDeliveryTime: 33,
                  slaString: "33 MINS",
                  lastMileTravel: 9.800000190734863,
                  slugs: {
                    restaurant: "sag-bucket-biryani-hanamkonda-hanamkonda",
                    city: "warangal",
                  },
                  cityState: "75",
                  address:
                    "2HC5+8RW, Kakatiya University Bypass Rd, Sagara Colony, Hanuman Nagar, Hanamkonda, Telangana 506009, India",
                  locality: "Sagara Colony",
                  parentId: 417061,
                  unserviceable: true,
                  veg: false,
                  select: false,
                  favorite: false,
                  tradeCampaignHeaders: [],
                  chain: [],
                  feeDetails: {
                    fees: [
                      { name: "distance", fee: 5200, message: "" },
                      { name: "time", fee: 1000, message: "" },
                      { name: "special", fee: 0, message: "" },
                    ],
                    totalFees: 6200,
                    message: "",
                    title: "Delivery Charge",
                    amount: "6200",
                    icon: "",
                  },
                  availability: {
                    opened: false,
                    nextOpenMessage: "",
                    nextCloseMessage: "",
                  },
                  longDistanceEnabled: 0,
                  rainMode: "NONE",
                  thirdPartyAddress: false,
                  thirdPartyVendor: "",
                  adTrackingID: "",
                  badges: {
                    imageBased: [],
                    textBased: [],
                    textExtendedBadges: [],
                  },
                  lastMileTravelString: "9.8 kms",
                  hasSurge: false,
                  sla: {
                    restaurantId: "697427",
                    deliveryTime: 33,
                    minDeliveryTime: 33,
                    maxDeliveryTime: 33,
                    lastMileTravel: 9.800000190734863,
                    lastMileDistance: 0,
                    serviceability: "SERVICEABLE_WITH_BANNER",
                    rainMode: "NONE",
                    longDistance: "NOT_LONG_DISTANCE",
                    preferentialService: false,
                    iconType: "EMPTY",
                  },
                  promoted: false,
                  avgRating: "--",
                  totalRatings: 0,
                  new: true,
                },
                subtype: "basic",
              },
            ],
            totalRestaurants: 99,
          },
          subtype: "personalized",
        },
        parentWidget: false,
      },
    ],
    nextPageFetch: 0,
  },
  tid: "c170cb2b-cf17-4cc0-bae1-14cd3af36f03",
  sid: "6hc67a9a-30ca-4fa4-83b7-f69349db82e8",
  deviceId: "c79bb082-1f73-be19-693f-fc5ec389e47d",
  csrfToken: "gBiZaYIEsy0u-DULOvxbRL5KxaYg_MENgJAm-94E",
};
